language: rust

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

# Cache cargo symbols for faster build
cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

rust:
  - nightly

# Dependencies of kcov, used for cargo-travis
addons:
  apt:
    packages:
      - libssl-dev

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH


# the main build
script:
  - |
      cargo build &&
      cargo test &&
      cargo doc

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    # Uncomment the following line for coveralls.io
    RUSTFLAGS="-C link-dead-code" cargo tarpaulin -v --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi